// <auto-generated />
namespace RSSWindowsForms
{
    partial class RssForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.buttonUpdateFeed = new System.Windows.Forms.Button();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.feedControl = new RSSWindowsForms.FeedControl();
            this.webBrowserFeedDetails = new System.Windows.Forms.WebBrowser();
            this.groupBox1.SuspendLayout();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox1.Controls.Add(this.buttonUpdateFeed);
            this.groupBox1.Controls.Add(this.textBox1);
            this.groupBox1.Location = new System.Drawing.Point(0, 0);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(658, 40);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "RSS Feed:";
            // 
            // buttonUpdateFeed
            // 
            this.buttonUpdateFeed.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonUpdateFeed.Location = new System.Drawing.Point(456, 10);
            this.buttonUpdateFeed.Name = "buttonUpdateFeed";
            this.buttonUpdateFeed.Size = new System.Drawing.Size(196, 23);
            this.buttonUpdateFeed.TabIndex = 1;
            this.buttonUpdateFeed.Text = "Load RSS Feed";
            this.buttonUpdateFeed.UseVisualStyleBackColor = true;
            this.buttonUpdateFeed.Click += new System.EventHandler(this.ButtonUpdateFeed_Click);
            // 
            // textBox1
            // 
            this.textBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.textBox1.Location = new System.Drawing.Point(7, 13);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(443, 20);
            this.textBox1.TabIndex = 0;
            this.textBox1.Text = "http://www.microsoft.com/feeds/msdn/en-us/rss.xml";
            // 
            // splitContainer1
            // 
            this.splitContainer1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.splitContainer1.Location = new System.Drawing.Point(0, 46);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.feedControl);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.webBrowserFeedDetails);
            this.splitContainer1.Size = new System.Drawing.Size(658, 721);
            this.splitContainer1.SplitterDistance = 360;
            this.splitContainer1.TabIndex = 1;
            // 
            // feedControl
            // 
            this.feedControl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.feedControl.Feed = null;
            this.feedControl.Location = new System.Drawing.Point(0, 0);
            this.feedControl.Name = "feedControl";
            this.feedControl.Size = new System.Drawing.Size(658, 360);
            this.feedControl.TabIndex = 0;
            this.feedControl.UriChanged += new System.EventHandler<RSSWindowsForms.UriChangedEventArgs>(this.FeedControl_UriChanged);
            // 
            // webBrowserFeedDetails
            // 
            this.webBrowserFeedDetails.Dock = System.Windows.Forms.DockStyle.Fill;
            this.webBrowserFeedDetails.Location = new System.Drawing.Point(0, 0);
            this.webBrowserFeedDetails.MinimumSize = new System.Drawing.Size(20, 20);
            this.webBrowserFeedDetails.Name = "webBrowserFeedDetails";
            this.webBrowserFeedDetails.Size = new System.Drawing.Size(658, 357);
            this.webBrowserFeedDetails.TabIndex = 0;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(658, 770);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.groupBox1);
            this.Name = "Form1";
            this.Text = "RSS Feed Reader";
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button buttonUpdateFeed;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private FeedControl feedControl;
        private System.Windows.Forms.WebBrowser webBrowserFeedDetails;
    }
}

